/*
Package util holds small, dependency-light helpers shared across the scheduler:
the pod identity/placement key and the label/annotation keys.

Identity/placement is read straight from the pod spec (decisions q6/q16/q21):
the placement key is (pod.Namespace, pod.Spec.ServiceAccountName). There is no
user.info, no webhook, no ownerRefs walk — the key on the pod is authoritative,
which is what makes indirect pods (a driver spawning executors) route correctly.
*/
package util

import (
	"fmt"

	corev1 "k8s.io/api/core/v1"
)

// Annotation/label keys. Canonical keys are arenadata.io/*; a couple of de-facto
// labels are accepted as fallback for app-id (decision q10 greenfield — no
// yunikorn.apache.org/* fallback).
const (
	AppIDAnnotation    = "arenadata.io/app-id"
	PodGroupAnnotation = "arenadata.io/pod-group"

	appIDLabel       = "applicationId"
	sparkAppSelector = "spark-app-selector"
	defaultSAName    = "default"
)

// Identity is a pod's placement key: (Namespace, ServiceAccount).
type Identity struct {
	Namespace      string
	ServiceAccount string
}

// PlacementKey returns the pod's identity/placement key, reading it straight
// from the spec. An empty spec.serviceAccountName resolves to "default" (the
// same defaulting the apiserver applies), so IsDefault can flag it.
func PlacementKey(pod *corev1.Pod) Identity {
	sa := pod.Spec.ServiceAccountName
	if sa == "" {
		sa = defaultSAName
	}
	return Identity{Namespace: pod.Namespace, ServiceAccount: sa}
}

// IsDefault reports whether the identity uses the namespace default SA. The
// default SA is banned in participating namespaces (decision q21) because it
// degrades the key to (namespace) alone.
func (id Identity) IsDefault() bool { return id.ServiceAccount == defaultSAName }

// String renders the identity as namespace/serviceaccount.
func (id Identity) String() string { return id.Namespace + "/" + id.ServiceAccount }

// AppID resolves a pod's application id: the arenadata.io/app-id annotation, then
// the de-facto applicationId / spark-app-selector labels, else an autogenerated
// ad-<namespace>-<uid>.
func AppID(pod *corev1.Pod) string {
	if v := pod.Annotations[AppIDAnnotation]; v != "" {
		return v
	}
	if v := pod.Labels[appIDLabel]; v != "" {
		return v
	}
	if v := pod.Labels[sparkAppSelector]; v != "" {
		return v
	}
	return fmt.Sprintf("ad-%s-%s", pod.Namespace, pod.UID)
}
