//go:build !ignore_autogenerated

/*
Deepcopy functions for scheduling.arenadata.io/v1alpha1.

Hand-written in the generated style for M0 (no controller-gen toolchain yet);
kept in the zz_generated file so a later `make generate` can replace it. Every
runtime.Object root implements DeepCopyObject.
*/
package v1alpha1

import (
	"maps"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in ResourceList) DeepCopyInto(out *ResourceList) {
	if in == nil {
		return
	}
	m := make(ResourceList, len(in))
	for k, v := range in {
		m[k] = v.DeepCopy()
	}
	*out = m
}

// DeepCopy returns a deep copy.
func (in ResourceList) DeepCopy() ResourceList {
	if in == nil {
		return nil
	}
	out := new(ResourceList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto copies the receiver into out.
func (in *PreemptionSpec) DeepCopyInto(out *PreemptionSpec) {
	*out = *in // Policy string, Delay metav1.Duration are value-copied
}

// DeepCopy returns a deep copy.
func (in *PreemptionSpec) DeepCopy() *PreemptionSpec {
	if in == nil {
		return nil
	}
	out := new(PreemptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *QueueLimit) DeepCopyInto(out *QueueLimit) {
	*out = *in
	if in.ServiceAccounts != nil {
		out.ServiceAccounts = make([]string, len(in.ServiceAccounts))
		copy(out.ServiceAccounts, in.ServiceAccounts)
	}
	if in.MaxResources != nil {
		in.MaxResources.DeepCopyInto(&out.MaxResources)
	}
}

// DeepCopy returns a deep copy.
func (in *QueueLimit) DeepCopy() *QueueLimit {
	if in == nil {
		return nil
	}
	out := new(QueueLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *QueueSpec) DeepCopyInto(out *QueueSpec) {
	*out = *in
	in.Guaranteed.DeepCopyInto(&out.Guaranteed)
	in.Max.DeepCopyInto(&out.Max)
	if in.Preemption != nil {
		out.Preemption = in.Preemption.DeepCopy()
	}
	if in.ServiceAccounts != nil {
		out.ServiceAccounts = make([]string, len(in.ServiceAccounts))
		copy(out.ServiceAccounts, in.ServiceAccounts)
	}
	if in.Limits != nil {
		out.Limits = make([]QueueLimit, len(in.Limits))
		for i := range in.Limits {
			in.Limits[i].DeepCopyInto(&out.Limits[i])
		}
	}
}

// DeepCopy returns a deep copy.
func (in *QueueSpec) DeepCopy() *QueueSpec {
	if in == nil {
		return nil
	}
	out := new(QueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *QueueStatus) DeepCopyInto(out *QueueStatus) {
	*out = *in
	in.EffectiveMax.DeepCopyInto(&out.EffectiveMax)
	in.Allocated.DeepCopyInto(&out.Allocated)
	in.Pending.DeepCopyInto(&out.Pending)
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

// DeepCopy returns a deep copy.
func (in *QueueStatus) DeepCopy() *QueueStatus {
	if in == nil {
		return nil
	}
	out := new(QueueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *Queue) DeepCopyInto(out *Queue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy.
func (in *Queue) DeepCopy() *Queue {
	if in == nil {
		return nil
	}
	out := new(Queue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy.
func (in *Queue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *QueueList) DeepCopyInto(out *QueueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]Queue, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopy returns a deep copy.
func (in *QueueList) DeepCopy() *QueueList {
	if in == nil {
		return nil
	}
	out := new(QueueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy.
func (in *QueueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *PodGroupSpec) DeepCopyInto(out *PodGroupSpec) {
	*out = *in
	in.MinResources.DeepCopyInto(&out.MinResources)
	if in.ScheduleTimeoutSeconds != nil {
		out.ScheduleTimeoutSeconds = new(int32)
		*out.ScheduleTimeoutSeconds = *in.ScheduleTimeoutSeconds
	}
	if in.MembersReadyTimeoutSeconds != nil {
		out.MembersReadyTimeoutSeconds = new(int32)
		*out.MembersReadyTimeoutSeconds = *in.MembersReadyTimeoutSeconds
	}
	if in.Desired != nil {
		out.Desired = new(int32)
		*out.Desired = *in.Desired
	}
	if in.Total != nil {
		out.Total = new(int32)
		*out.Total = *in.Total
	}
}

// DeepCopy returns a deep copy.
func (in *PodGroupSpec) DeepCopy() *PodGroupSpec {
	if in == nil {
		return nil
	}
	out := new(PodGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *PodGroupStatus) DeepCopyInto(out *PodGroupStatus) {
	*out = *in
	in.ReservedResources.DeepCopyInto(&out.ReservedResources)
	if in.OccupiedNodes != nil {
		m := make(map[string]int32, len(in.OccupiedNodes))
		maps.Copy(m, in.OccupiedNodes)
		out.OccupiedNodes = m
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

// DeepCopy returns a deep copy.
func (in *PodGroupStatus) DeepCopy() *PodGroupStatus {
	if in == nil {
		return nil
	}
	out := new(PodGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *PodGroup) DeepCopyInto(out *PodGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy.
func (in *PodGroup) DeepCopy() *PodGroup {
	if in == nil {
		return nil
	}
	out := new(PodGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy.
func (in *PodGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *PodGroupList) DeepCopyInto(out *PodGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]PodGroup, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopy returns a deep copy.
func (in *PodGroupList) DeepCopy() *PodGroupList {
	if in == nil {
		return nil
	}
	out := new(PodGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy.
func (in *PodGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
